main: main.cpp tsp.hpp util.hpp nearest_neighbor.hpp nearest_insertion.hpp farthest_insertion.hpp double_mst.hpp greedy.hpp quick_boruvka.hpp two_opt.hpp
	g++ -Wall -Ofast -mtune=native -std=c++11 -o main main.cpp
